#!/bin/bash

set -eu

to="$1"
from="$2"

w="${WHAMI-`whami`}"

/opt/chj/ssh-config-gen/filter_file "$from" \
| cpp -Dnetwork_"$w"=1 \
| /opt/chj/bin/filter_whitespace > ."$to".new

mv ."$to".new "$to"
