#!/bin/bash

set -eu

where="$1"

CONFIGDIR=..

# network_"$where"=1 make

whereq=`printf '%q' "$where"`

FILTER_FILE=`readlink -f filter_file`

cd "$CONFIGDIR"

"$FILTER_FILE" config-in > .config.pre

cpp -D"network_$where=1" < .config.pre > .config.tmp

mv .config.tmp .config
