#!/bin/bash

set -eu

where="$1"

CONFIGDIR=/etc/ssh

# network_"$where"=1 make

whereq=`printf '%q' "$where"`

FILTER_FILE=`readlink -f filter_file`

cd "$CONFIGDIR"

"$FILTER_FILE" ssh_config-in > .ssh_config.pre

cpp -D"network_$where=1" < .ssh_config.pre > .ssh_config.tmp

mv .ssh_config.tmp ssh_config
